Вычисления с Numpy

In [3]:
import numpy as np

Задание 1 (Делал с использованием создания случайного многомерного массива)

In [93]:
a = np.random.randint(0, 50, (5,2))

In [110]:
a = np.array([[1,6],
            [2,8],
            [3,11],
            [3,10],
            [1,7]])

In [94]:
a

array([[11, 33],
       [42, 37],
       [44, 36],
       [48, 15],
       [46, 11]])

In [111]:
mean_a = a.mean(axis=0)

In [112]:
mean_a

array([2. , 8.4])

Задание 2

In [113]:
a_centered = a - mean_a

In [114]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

Задание 3

In [115]:
a_centered_sp = np.prod(a_centered, axis=0)

In [116]:
a_centered_sp

array([ 0.     , -5.59104])

In [ ]:
a_centered_sp2 = np.dot(a_centered_sp, a_centered_sp)

In [123]:
a_centered_sp2

31.259728281600054

In [132]:
result = np.divide(a_centered_sp2,a_centered_sp.shape[0] - 1)

In [133]:
result

31.259728281600054

Другой вариант с другим ответом))

In [124]:
a_centered_s = a_centered.sum(axis=0)

In [125]:
a_centered_s

array([ 0.00000000e+00, -1.77635684e-15])

In [126]:
a_centered_sp3 = np.dot(a_centered_s, a_centered_s)

In [127]:
a_centered_sp3

3.1554436208840472e-30

In [134]:
result2 = np.divide(a_centered_sp3,a_centered_sp.shape[0] - 1)

In [135]:
result2

3.1554436208840472e-30